### ISSUE TITLE
Chaos worker experiments fail

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#247] opened 2021-03-08 12:57 UTC
Error message in log:

```
zbctl create instance benchmark --insecure\n+ workflowInstanceKey=\'{\n  "workflowKey":  "2251799813685369",\n  "bpmnProcessId":  "benchmark",\n  "version":  1,\n  "workflowInstanceKey":  "4503599627370568"\n}\'\n++ echo \'{\n  "workflowKey":  "2251799813685369",\n  "bpmnProcessId":  "benchmark",\n  "version":  1,\n  "workflowInstanceKey":  "4503599627370568"\n}\'\n++ jq .workflowInstanceKey\n+ workflowInstanceKey=\'"4503599627370568"\'\n/home/chaos/zeebe-chaos/chaos-experiments/camunda-cloud/../scripts/verify-steady-state.sh: line 27: "4503599627370568": syntax error: operand expected (error token is ""4503599627370568"")\n'}'
[2021-03-08 10:31:07 DEBUG] [__init__:355] No controls to apply on 'activity'
```

**Comment by Zelldon** [comment] 2021-03-09 07:17
I tried it with docker and running this scripts (adjusted it in a way that it not uses kubectl), but can't reproduce it. I tried several zbctl version (0.26.0 and 0.26.1 and something older)

```
[zell scripts/ cluster: zeebe-cluster ns:testbench]$ zbctl version
zbctl 0.26.0 (commit: 7e50628e)
[zell scripts/ cluster: zeebe-cluster ns:testbench]$ ./verify-steady-state.sh 1
+ '[' -z 1 ']'
+ source utils.sh
++ CHAOS_SETUP=cloud
+ requiredPartition=1
+ retryUntilSuccess startInstancesOnPartition
+ echo 'Run '\''startInstancesOnPartition'\'''
Run 'startInstancesOnPartition'
+ startInstancesOnPartition
+ partition=0
+ [[ 0 -eq 1 ]]
++ zbctl create instance benchmark --insecure
+ workflowInstanceKey='{
  "workflowKey": 2251799813685249,
  "bpmnProcessId": "benchmark",
  "version": 1,
  "workflowInstanceKey": 2251799813685263
}'
++ echo '{
  "workflowKey": 2251799813685249,
  "bpmnProcessId": "benchmark",
  "version": 1,
  "workflowInstanceKey": 2251799813685263
}'
++ jq .workflowInstanceKey
+ workflowInstanceKey=2251799813685263
+ partition=1
+ echo 'Started workflow with key 2251799813685263, corresponding partition 1'
Started workflow with key 2251799813685263, corresponding partition 1
+ [[ 1 -eq 1 ]]

```

I will try with cloud setup.

**Comment by Zelldon** [comment] 2021-03-09 07:34
When I run this with a camunda cloud setup It get this error:

```
+ partition=0
+ [[ 0 -eq 1 ]]
++ kubectl exec zeebe-0 -n c60ed173-0b8a-41c3-a488-f458695ac165-zeebe -- zbctl create instance benchmark --insecure
+ workflowInstanceKey='{
  "workflowKey":  "2251799813685250",
  "bpmnProcessId":  "benchmark",
  "version":  1,
  "workflowInstanceKey":  "2251799813685252"
}'
++ echo '{
  "workflowKey":  "2251799813685250",
  "bpmnProcessId":  "benchmark",
  "version":  1,
  "workflowInstanceKey":  "2251799813685252"
}'
++ jq .workflowInstanceKey
+ workflowInstanceKey='"2251799813685252"'
./verify-steady-state.sh: line 27: "2251799813685252": syntax error: operand expected (error token is ""2251799813685252"")
```

wtf?

**Comment by Zelldon** [comment] 2021-03-09 08:19
If we keep the keys as values then we could cast via jq the value to int. 

```
jq '.workflowInstanceKey|tonumber'
```

**Comment by npepinpe** [comment] 2021-03-09 08:44
@MiguelPires please fix as part of medic duties since all the chaos tests will fail at the moment.

**Comment by MiguelPires** [comment] 2021-03-09 13:33
I've asked @pihme to take this over as I'm currently swamped with other support/medic duties. Thanks @pihme

**Comment by Zelldon** [comment] 2021-03-23 07:11
I think we can close this - was fixed in the chaos repo by @pihme thanks

**Closed by Zelldon** 2021-03-23 07:11 UTC
Labels: Status: Ready, bug
