### ISSUE TITLE
E2E protocol unable to map generation UUIDs

### ISSUE THREAD

**Issue by koevskinikola** [zeebe-io/zeebe-cluster-testbench#941] opened 2023-11-17 11:55 UTC
Our process `e2e_testbench_protocol` isn't able to map the generations to UUIDs and an incident is raised.

The following exception is shown:
```
java.lang.IllegalArgumentException: Unable to find generation '65c787fb-f73d-4a2b-a947-2c4c3b260763'; closest candidates: ['acbb44eb-0923-4b2a-83a9-151937b2f7df', 'f39cedf0-6da8-40f3-aa90-0cf7fbb6de8b', 'bf2a061d-1a33-4123-bf7a-c14cb933f139']; available candidates: ['1bede723-f469-456f-9449-ae6b7a064ae0', 'dce9bbfa-06c2-4563-a3af-b3c7d3999fe9', 'f6cea02b-dc98-4335-9f0c-faba94e8d230', '6d7ad8f0-5948-4404-9383-87399a554110', '4a80d8a3-c5e2-4d20-8653-504acb14eb73', 'a941b647-4084-4d7f-be60-83f08e469bbb', '6cfd80be-f32f-4291-885a-63e6673e4441', '13283d40-fdfa-4e8b-b7f8-aeddd6dd07ad', '60676316-d53d-42e5-b79d-7314097fac28', '7d0ab39a-e957-4457-8302-5fb97e556869', 'f32dd0e6-8ef7-4855-b715-ae454a32c5e0', '1f9213f5-7781-4fc1-859d-4639411e8ffa', '7b4a61f8-55f5-4219-abd3-f4a554749dbc', 'acbb44eb-0923-4b2a-83a9-151937b2f7df', 'cfdcfc5d-8c99-49be-a396-6464d5fab645', '06ca3dd9-8d63-4b59-bf30-05e5f384938e', '74ab4eea-ba18-49d8-9066-e02753fd7664', '6e16431e-b49f-4df7-9abc-6adc5a82a898', '30edad6e-85b3-4fa0-9357-1ff6993db4bf', '50c15215-efa5-41a7-9a0f-8463720acc35', 'c0a2373d-8e24-4509-a845-3a75bdca438a', '94b299e7-f602-4a3e-baf0-20cd867917ea', '6a37b6e0-a5bf-4ffb-9cb4-5a104bad7c44', 'dc615859-98b9-48ff-9f6c-046f3c129e9e', '9f6ab595-bfbb-4a13-8bd3-84eebdee0d3e', '170e5a39-1901-4e52-87eb-8e6657e4d1fe', 'ad079f43-3f83-42e3-aabc-e99cd7de569c', '07ccfc44-0c41-4318-b7f5-65c2afc37d7c', '07aa03f8-c53b-4650-80ca-81865480a442', '3a5309b9-5890-49d6-af2e-d88627ffe123', '4495a935-b0e4-4e05-bc36-fd19e455e4f4', 'd7d8a253-0771-423f-9327-139546afbc2b', 'df53a5c3-a6bc-4180-b062-d1b9d977eb1d', '6dbdc8ac-34d8-433c-9cff-ab94294d154c', '7b0d03d0-811c-437a-878a-67db73940605', '3693d923-2344-48d7-acd3-f1b1d31d0662', '0e6d5a7e-8e8e-481a-bb78-bd9dc5da4054', 'c52b7f02-e284-4956-800f-e48f179568d9', 'cc5c11e3-e7ab-4312-9a46-df4ba050525c', 'aef17377-ff9b-4734-bad6-5e71cd96b990', '4c4a19c2-3412-4770-8380-2c39c1e51559', '02bd3686-aea4-4b23-bbb0-47c4e1c97812', '6d568596-0d2a-4e6e-9b2d-0929a98ee50a', 'eb946c6b-ae3c-4cd9-8d58-6cea078c022f', 'f39cedf0-6da8-40f3-aa90-0cf7fbb6de8b', 'bf2a061d-1a33-4123-bf7a-c14cb933f139', '40e1f202-af3f-45a9-8773-a75172e44c36', '78b39545-ec94-4eeb-9224-82dddfb6889f', 'e55821ce-8169-4128-b2e4-2238a77837d3', '4e4f2aa4-e68e-4dd9-a038-3bb1bdc79b8c', 'b4027591-144a-410a-9b5c-d6a2d9a3978c', '85eeecab-d2f8-4dba-bcdd-6deca207d0cc', '76895e6d-7f8b-4f7a-b30e-3326f669d9b3', '14becfc0-d7f2-451c-8344-b2608e767f8e', '2593dc8e-734b-4e83-8eb5-f1aeb4fdc7d6', '1f550983-5c02-4fdc-96cb-7ffb5e46d8bd', 'a0b58424-353a-41d3-8e06-54eeeb5d9739', 'fd1094fb-37d4-48cb-bbd3-b7517e6adacb', '0af5dec2-1c5f-4465-8393-a27212ead646', '6090575b-04d7-43fa-9901-15d083630308', '6e5743fe-7274-46a0-bdac-b6a263663879', '20455d44-e09f-4b6e-9c85-a2df0de86915']
```

**Comment by nicpuppa** [comment] 2023-11-17 12:01
Hey @Zelldon this is the same error that I saw last week, we had a discussion about this on [this slack thread](https://camunda.slack.com/archives/C013MEVQ4M9/p1699450138707339)

**Comment by Zelldon** [comment] 2023-11-17 12:06
I will take care of it next week @nicpuppa @koevskinikola

**Comment by Zelldon** [comment] 2023-11-21 10:13
Duplicate of https://github.com/camunda/zeebe/issues/14780

**Closed by Zelldon** 2023-11-21 10:13 UTC
Labels: bug
