### ISSUE TITLE
Show in Google Test Result sheet the Test name

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#153] opened 2020-11-18 11:06 UTC
Currently in the test sheet it is not visible which test has been exeucted would cool to have this info as a separate column.

**Comment by pihme** [comment] 2020-11-18 11:14
duplicate of #124

**Closed by pihme** 2020-11-18 11:14 UTC

**Comment by Zelldon** [comment] 2020-11-18 11:16
Ah sorry have overseen this

**Comment by pihme** [comment] 2020-11-18 11:30
yeah, the issues list is getting a little long for my liking. I will do some culling
